### ISSUE TITLE
Fails the first time it is run.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/ddu.vim#11]
# Problems summary
Fails the first time it is run.
However, after the second time, it succeeds.

## Expected
Succeeds the first time it is run.

## Environment Information

- ddu.vim version (SHA1): ca165d2dff780388d180bc41e174ee1cf2717ff9

- denops.vim version (SHA1): 788c6702aec71544c575766d79c399dec6e7a26c

- deno version(`deno -V` output): deno 1.19.0

- OS: Mac

- neovim/Vim `:version` output:
```
NVIM v0.7.0-dev+1115-g5cb45dffb
Build type: Release
LuaJIT 2.1.0-beta3
```

- `:checkhealth` or `:CheckHealth` result(neovim only): OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
if &compatible
    set nocompatible
endif
let $CACHE = expand('~/.cache')
if !isdirectory(expand($CACHE))
    call mkdir(expand($CACHE), 'p')
endif
let s:dein_dir = expand('$CACHE/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    execute 'set runtimepath^=' . s:dein_repo_dir
endif

call dein#begin(s:dein_dir, expand('<sfile>'))

call dein#load_toml('~/.config/nvim/dein/deinlazy.toml', {'lazy': 1})

call dein#end()

filetype plugin indent on
syntax enable
```

deinlazy.toml
```toml
# Using Deno on plugin
[[plugins]]
repo = 'vim-denops/denops.vim'
[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
hook_source = '''
call ddu#custom#patch_global({
    \ 'ui': 'ff',
    \ })
'''
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Start Neovim.
2. Run `call dein#update()` command.
3. Restart Neovim.
4. Run `call ddu#start({'sources': [{'name': 'file_rec'}]})` command.

## Screenshot (if possible)
![スクリーンショット 2022-02-20 0 34 00](https://user-images.githubusercontent.com/3197942/154807618-530e79ea-66ae-4bb7-81eb-7feb66f43556.png)

This error will occur even if you do not lazy load `denops.vim`.
![スクリーンショット 2022-02-20 1 03 12](https://user-images.githubusercontent.com/3197942/154808697-b4441232-f362-4a74-ade0-5086405bede5.png)
